
<div class="page-title">
    <h1><?php echo $this->__('Almost done!') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Please confirm your order') ?></h2>

<p>Touch Payments has sent you an SMS containing a confirmation link. Once you tap on it and visit it using your
browser your putchase will be confirmed. Please note that we will save the order for the next 20 minutes and it
will be automatically cancelled if you don't confirm it.</p>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
